# Configures dependabot

version: 2
updates:
  # NPM packages
  - package-ecosystem: 'npm'
    directory: '/src-vue'
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  # Rust crates
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
